spring.application.name=requestmanagement

server.servlet.context-path=/api/v1

spring.datasource.url=jdbc:postgresql://localhost:5432/requestmanagement
spring.datasource.username=postgres
spring.datasource.password=sa

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.liquibase.enabled=true
spring.liquibase.liquibase-schema=public